//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TYPWebApplication
{


    public partial class Stylereports
    {

        /// <summary>
        /// check control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl check;

        /// <summary>
<<<<<<< HEAD
        /// stylesrepo control.
=======
<<<<<<< HEAD
        /// stylesrepo control.
=======
<<<<<<< HEAD
        /// stylesrepo control.
=======
        /// qna control.
>>>>>>> f80f60440ae79f41501455be8766ed5efa98804d
>>>>>>> b79a4c32eef165f10b6cd8d1ccb938d8a4786b56
>>>>>>> 6edc56f6fbcb07fc274e4c05a6172bbf9fad7097
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> b79a4c32eef165f10b6cd8d1ccb938d8a4786b56
>>>>>>> 6edc56f6fbcb07fc274e4c05a6172bbf9fad7097
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl stylesrepo;

        /// <summary>
        /// employ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl employ;
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
=======
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl qna;
>>>>>>> f80f60440ae79f41501455be8766ed5efa98804d
>>>>>>> b79a4c32eef165f10b6cd8d1ccb938d8a4786b56
>>>>>>> 6edc56f6fbcb07fc274e4c05a6172bbf9fad7097
    }
}
